# Generated by Django 3.2.16 on 2022-10-19 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5d438d76-f23b-4589-a9c8-6d9a3cad7615'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('topic_text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated', models.DateField(auto_now=True, verbose_name='last update date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['topic_text'],
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry', to='polls.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registry',
                'verbose_name_plural': 'Registrys',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.topic'),
        ),
        migrations.AddField(
            model_name='choice',
            name='registrys',
            field=models.ManyToManyField(related_name='registrys', through='polls.Registry', to=settings.AUTH_USER_MODEL),
        ),
    ]
