# Generated by Django 3.2.16 on 2022-10-19 23:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0947ee6d-4259-4ecb-aeaa-0ad274269688'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
