# Generated by Django 3.2.16 on 2022-10-19 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20221019_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b9e7a1a-e44f-43bb-92ee-18e2dcdf97bf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
