# Generated by Django 4.1 on 2022-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_cool_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='cool_users',
        ),
        migrations.AlterField(
            model_name='question',
            name='private_question',
            field=models.BooleanField(default=True, verbose_name='private question'),
        ),
    ]
