# Generated by Django 3.2.16 on 2022-10-20 01:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20221019_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1667efd8-cccb-4090-b1f1-52bdc0cf17e7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
