# Generated by Django 3.2.16 on 2022-10-20 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.UUIDField(default=uuid.UUID('73ec12db-a4cd-41bc-a2bf-32946e32227a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
