# Generated by Django 3.2.16 on 2022-10-30 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_auto_20221019_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('214f35c2-64c8-4090-bba6-dc3ef5590d7b'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('topic_name', models.CharField(max_length=200)),
                ('randomize_choice_order', models.BooleanField(default=True)),
                ('poll_type', models.CharField(choices=[('private', 'Private')], default='private', max_length=250)),
                ('poll_info_url', models.CharField(max_length=300, null=True)),
                ('openvot', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated', models.DateField(auto_now=True, verbose_name='last update date')),
                ('voting_starts_at', models.DateTimeField(default=None, null=True)),
                ('voting_ends_at', models.DateTimeField(default=None, null=True)),
                ('voting_started_at', models.DateTimeField(default=None, null=True)),
                ('voting_ended_at', models.DateTimeField(default=None, null=True)),
                ('result_released_at', models.DateTimeField(default=None, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'Registry',
                'verbose_name_plural': 'Registrys',
            },
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='registrys',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registry', to='polls.choice'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.poll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.ManyToManyField(related_name='votes', through='polls.Vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
