# Generated by Django 3.2.16 on 2022-10-30 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1cde0b15-5adb-46ee-9d69-e0fbe3cd6adc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
