# Generated by Django 3.2.16 on 2022-10-30 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_poll_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='topic_name',
            new_name='poll_name',
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065f4cbc-79f6-4482-a10a-e42e082c111f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
