# Generated by Django 3.2.16 on 2022-10-30 19:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20221030_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='result_released_at',
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c7f93f05-aeaf-48d7-9b42-4e00848699c3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_info_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voting_ends_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voting_starts_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
