# Generated by Django 3.2.16 on 2022-10-31 22:38

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20221030_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='poll_info_url',
        ),
        migrations.AddField(
            model_name='poll',
            name='num_choices_max',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
